M48
; DRILL file {KiCad (7.0.0)} date Fri Mar 31 05:55:32 2023
; FORMAT={3:3/ absolute / metric / suppress trailing zeros}
; #@! TF.CreationDate,2023-03-31T05:55:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC,LZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X11Y-0923
X11Y-1007
X171Y-0923
X171Y-1007
T0
M30
